/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ingreso.java
 *
 * Created on 30-jul-2015, 13:12:44
 */
package proyectofinaldes;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class Ingreso extends javax.swing.JFrame {

    /** Creates new form Ingreso */
    public Ingreso() {
        initComponents();
        txtUsuario.requestFocus();
        lblAviso.setVisible(false);
        jDesktopPane1.setBorder(new ImagenFondo());
        this.setSize(600, 300);
        this.setLocationRelativeTo(null);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        lblAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/users.png"))); // NOI18N
        jLabel1.setBounds(180, 80, 48, 48);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/key.png"))); // NOI18N
        jLabel3.setBounds(180, 150, 46, 48);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtClave.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });
        txtClave.setBounds(250, 150, 169, 40);
        jDesktopPane1.add(txtClave, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtUsuario.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        txtUsuario.setBounds(250, 80, 169, 40);
        jDesktopPane1.add(txtUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblAviso.setBackground(new java.awt.Color(0, 0, 0));
        lblAviso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAviso.setText("EL USUARIO O LA CLAVE SON INCORRECTOS");
        lblAviso.setBounds(170, 230, 280, 14);
        jDesktopPane1.add(lblAviso, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
// TODO add your handling code here:
    
    Conexion cc = new Conexion();
    Connection cn = cc.conexion();
    String sql="";
    sql="select * from usuario";
        try {
            Statement psd=cn.createStatement();
            ResultSet rs=psd.executeQuery(sql);
            while(rs.next()){
                if((txtUsuario.getText().equals(rs.getString("cienc"))) && (txtClave.getText().equals(rs.getString("pasenc")))){
                    if(rs.getString("rolenc").equals("ADMINISTRADOR")){
                    menu mn=new menu(txtUsuario.getText());
                    mn.setExtendedState(MAXIMIZED_BOTH);
                    mn.setVisible(true);
                    this.dispose();                    
                                        JOptionPane.showMessageDialog(null, "Bienvenido"+" "+rs.getString("nom"));
                    
                    }else if(rs.getString("rolenc").equals("VENDEDOR")){
                    menu mn=new menu(txtUsuario.getText());
                    mn.setExtendedState(MAXIMIZED_BOTH);
                    mn.setVisible(true);
                    this.dispose();   
                    mn.jMenuItem1.setEnabled(false);
                    mn.jMenuItem1.setVisible(false);
                    mn.jMenuItem2.setEnabled(true);
                    mn.jMenu2.setVisible(false);
                    mn.jMenu3.setVisible(false);
                    //mn.jMenuItem4.setEnabled(true);
                                        JOptionPane.showMessageDialog(null, "Bienvenido"+" "+rs.getString("nom"));
                    }
                }else{
                    lblAviso.setVisible(true);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    
}//GEN-LAST:event_txtClaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
